# Generated by Django 4.2 on 2023-04-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carddeck", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardgroup",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
