# Generated by Django 4.1.7 on 2023-05-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carddeck", "0002_alter_cardgroup_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="level",
            field=models.IntegerField(default=0),
        ),
    ]
